version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    minor-patch:
      update-types:
        - minor
        - patch
    codeql:
      patterns:
        - github/codeql-action/*
  schedule:
    interval: "weekly"
- package-ecosystem: "gomod"
  directory: "/"
  allow:
  - dependency-type: all
  groups:
    minor-patch:
      update-types:
        - minor
        - patch
  schedule:
    interval: "weekly"
